name          'chartbeat-sysstat'
version       '0.0.2'
source        'https://github.com/chartbeat-labs/puppet-sysstat'
author        'chartbeat'
license       'MIT'
summary       'Module to manage sysstat'
description   'Sysstat module for Puppet'
project_page  'https://github.com/chartbeat-labs/puppet-sysstat'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
